# Generated by Django 4.2.9 on 2024-01-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='likes',
            field=models.IntegerField(null=True),
        ),
    ]
