# Generated by Django 4.2.9 on 2024-01-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_music_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='music',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
