# Generated by Django 4.2.9 on 2024-01-29 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_customuser_status_customuser_is_banned'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
