# Generated by Django 4.2.9 on 2024-01-31 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_music_audio_file'),
        ('main', '0012_ban'),
    ]

    operations = [
    ]
