# Generated by Django 4.2.9 on 2024-01-31 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_music_audio_file'),
        ('main', '0015_history'),
    ]

    operations = [
    ]
