# Generated by Django 4.2.9 on 2024-01-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='type',
            field=models.CharField(choices=[('Pop', 'Pop'), ('Rock', 'Rock'), ('Folk', 'Folk'), ('Jazz', 'Jazz'), ('Classic', 'Classic')], default='Pop', max_length=10),
        ),
    ]
